[tool.poetry]
name = "xgglblast"
version = "0.1.0"
description = ""
authors = ["JamesCurtis <jamescurtis@foxmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
grequests = "^0.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
